apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-app-config
  labels:
    app: microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app
  template:
    metadata:
      labels:
        app: microservice-app
    spec:
      containers:
        - name: config-server
          image: haydikodlayalim/config-server:10.0.1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: microservice-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
